# Generated by Django 4.2.28 on 2026-02-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='B-CLUB', max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('theme_color', models.CharField(default='#eab308', max_length=20)),
                ('table_a_color', models.CharField(default='#10b981', max_length=20)),
                ('table_b_color', models.CharField(default='#3b82f6', max_length=20)),
                ('rate_base', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('rate_reduced', models.DecimalField(decimal_places=2, default=135, max_digits=10)),
                ('threshold_mins', models.IntegerField(default=15)),
                ('floor_min', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('floor_mid', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PS4Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=10)),
                ('player_options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PS4Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('game_name', models.CharField(max_length=255)),
                ('players', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=10)),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['date'], name='api_ps4sess_date_aa7f66_idx')],
            },
        ),
        migrations.CreateModel(
            name='BilliardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=1)),
                ('start_time', models.CharField(max_length=20)),
                ('stop_time', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=10)),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['date'], name='api_billiar_date_873e6a_idx'), models.Index(fields=['table_id'], name='api_billiar_table_i_bfe576_idx')],
            },
        ),
        migrations.CreateModel(
            name='BarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=10)),
                ('timestamp', models.BigIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['date'], name='api_barorde_date_09c681_idx')],
            },
        ),
        migrations.CreateModel(
            name='PS4TimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('players', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='api.ps4game')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='api_ps4time_game_id_50b13d_idx')],
            },
        ),
    ]
