# Generated by Django 4.2.28 on 2026-02-05

from django.db import migrations, models
from datetime import datetime


def convert_time_to_datetime(apps, schema_editor):
    BilliardSession = apps.get_model('api', 'BilliardSession')
    for session in BilliardSession.objects.all():
        try:
            # Convert start_time (HH:MM:SS format) to DateTime
            if session.start_time:
                # Use a default date (the session's date field)
                date_str = str(session.date) if session.date else '1970-01-01'
                try:
                    dt = datetime.strptime(f"{date_str} {session.start_time}", "%Y-%m-%d %H:%M:%S")
                    session.start_time_new = dt
                except ValueError:
                    # If date parsing fails, use a default
                    session.start_time_new = datetime(1970, 1, 1, 0, 0, 0)
            
            # Convert stop_time (HH:MM:SS format) to DateTime
            if session.stop_time:
                date_str = str(session.date) if session.date else '1970-01-01'
                try:
                    dt = datetime.strptime(f"{date_str} {session.stop_time}", "%Y-%m-%d %H:%M:%S")
                    session.stop_time_new = dt
                except ValueError:
                    session.stop_time_new = None
            
            # Convert date (YYYY-MM-DD format) to DateField
            if session.date:
                try:
                    session.date_new = datetime.strptime(str(session.date), "%Y-%m-%d").date()
                except ValueError:
                    session.date_new = datetime(1970, 1, 1).date()
            
            session.save(update_fields=['start_time_new', 'stop_time_new', 'date_new'])
        except Exception as e:
            print(f"Error converting session {session.id}: {e}")


def reverse_convert(apps, schema_editor):
    BilliardSession = apps.get_model('api', 'BilliardSession')
    for session in BilliardSession.objects.all():
        try:
            if session.start_time_new:
                session.start_time = session.start_time_new.strftime('%H:%M:%S')
            if session.stop_time_new:
                session.stop_time = session.stop_time_new.strftime('%H:%M:%S')
            if session.date_new:
                session.date = session.date_new.strftime('%Y-%m-%d')
            session.save(update_fields=['start_time', 'stop_time', 'date'])
        except Exception as e:
            print(f"Error reversing session {session.id}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # Add new temporary fields
        migrations.AddField(
            model_name='billiardsession',
            name='start_time_new',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='billiardsession',
            name='stop_time_new',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='billiardsession',
            name='date_new',
            field=models.DateField(null=True, blank=True),
        ),
        # Run data migration
        migrations.RunPython(convert_time_to_datetime, reverse_convert),
        # Remove old fields
        migrations.RemoveField(
            model_name='billiardsession',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='billiardsession',
            name='stop_time',
        ),
        migrations.RemoveField(
            model_name='billiardsession',
            name='date',
        ),
        # Rename new fields to original names
        migrations.RenameField(
            model_name='billiardsession',
            old_name='start_time_new',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='billiardsession',
            old_name='stop_time_new',
            new_name='stop_time',
        ),
        migrations.RenameField(
            model_name='billiardsession',
            old_name='date_new',
            new_name='date',
        ),
    ]
